Add CI workflow to check Markdown files for problems
On every push and pull request that affects relevant files, and periodically, check the repository's Markdown files for
problems:

- Use markdownlint to check for common problems and formatting.
- Use markdown-link-check to check for broken links.

The Arduino tooling Markdown style is defined by the `.markdownlint.yml` file.

In the event the repository contains externally maintained Markdown files, markdownlint can be configured to ignore them
via a `.markdownlintignore` file:
https://github.com/igorshubovych/markdownlint-cli#ignoring-files

markdown-link-check is configured via the `.markdown-link-check.json` file:
https://github.com/tcort/markdown-link-check#config-file-format

This duplicates the link check capability previously provided by the "Check links" workflow, so that has been removed.

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -110,90 +110,23 @@ tasks:
     cmds:
       - go fmt {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}
 
-  python:check:
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
+  markdown:lint:
+    desc: Check for problems in Markdown files
     cmds:
-      - task: python:lint
+      - npx markdownlint-cli "**/*.md"
 
-  python:lint:
-    desc: Lint Python code
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
+  markdown:fix:
+    desc: Automatically correct linting violations in Markdown files where possible
     cmds:
-      - poetry install --no-root
-      - poetry run flake8
+      - npx markdownlint-cli --fix "**/*.md"
 
-  python:format:
-    desc: Automatically formats Python files
-    cmds:
-      - poetry install --no-root
-      - poetry run black .
-
-  docs:gen:
-    desc: Generate command reference
-    dir: ./docsgen
-    cmds:
-      # docs will generate examples using os.Args[0] so we need to call
-      # the generator `arduino-lint`
-      - go build -o arduino-lint{{exeExt}}
-      # we invoke `arduino-lint` like this instead of `./arduino-lint` to remove
-      # the `./` chars from the examples
-      - PATH=. arduino-lint ../docs/commands
-      - task: docs:format
-
-  docs:build:
-    desc: Build documentation website contents
-    cmds:
-      - task: docs:gen
-      - poetry install --no-root
-      - poetry run mkdocs build --strict
-
-  docs:publish:
-    desc: Use Mike to build and push versioned docs
-    cmds:
-      - task: docs:gen
-      - poetry run mike deploy --update-aliases --push --remote {{.DOCS_REMOTE}} {{.DOCS_VERSION}} {{.DOCS_ALIAS}}
-
-  docs:serve:
-    desc: Run documentation website locally
-    cmds:
-      - task: docs:build
-      - poetry run mkdocs serve
-
-  docs:check:
-    desc: Lint and check formatting of documentation files
-    cmds:
-      - task: docs:check-formatting
-      - task: docs:check-links
-
-  docs:lint:
-    desc: Lint documentation files
-    cmds:
-      - task: docs:check-license
-
-  docs:check-license:
-    desc: Check if the license file is correctly formatted
-    cmds:
-      - |
-        EXPECTED_LICENSE_FILE="\"LICENSE.txt\""
-        EXPECTED_LICENSE_TYPE="\"GPL-3.0\"" # https://spdx.org/licenses/
-
-        # See: https://github.com/licensee/licensee
-        LICENSEE_OUTPUT="$(licensee detect --json --confidence=100)"
-
-        DETECTED_LICENSE_FILE="$(echo "$LICENSEE_OUTPUT" | jq .matched_files[0].filename | tr --delete '\r')"
-        echo "Detected license file: $DETECTED_LICENSE_FILE"
-        if [ "$DETECTED_LICENSE_FILE" != "$EXPECTED_LICENSE_FILE" ]; then
-          echo "ERROR: detected license file doesn't match expected: $EXPECTED_LICENSE_FILE"
-          exit 1
-        fi
-
-        DETECTED_LICENSE_TYPE="$(echo "$LICENSEE_OUTPUT" | jq .matched_files[0].matched_license | tr --delete '\r')"
-        echo "Detected license type: $DETECTED_LICENSE_TYPE"
-        if [ "$DETECTED_LICENSE_TYPE" != "$EXPECTED_LICENSE_TYPE" ]; then
-          echo "ERROR: detected license type doesn't match expected $EXPECTED_LICENSE_TYPE"
-          exit 1
-        fi
-
-  docs:check-links:
-    desc: Check for dead links in documentation
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
+  markdown:check-links:
+    desc: Check for broken links
+    deps:
+      - task: docs:generate
     cmds:
       - |
         if [[ "{{.OS}}" == "Windows_NT" ]]; then
@@ -230,6 +163,95 @@ tasks:
             done
             exit $STATUS
           '
+        fi
+
+  python:check:
+    cmds:
+      - task: python:lint
+
+  python:lint:
+    desc: Lint Python code
+    cmds:
+      - poetry install --no-root
+      - poetry run flake8
+
+  python:format:
+    desc: Automatically formats Python files
+    cmds:
+      - poetry install --no-root
+      - poetry run black .
+
+  docs:generate:
+    desc: Create all generated documentation content
+    deps:
+      - task: docs:gen
+
+  docs:gen:
+    desc: Generate command reference
+    dir: ./docsgen
+    cmds:
+      # docs will generate examples using os.Args[0] so we need to call
+      # the generator `arduino-lint`
+      - go build -o arduino-lint{{exeExt}}
+      # we invoke `arduino-lint` like this instead of `./arduino-lint` to remove
+      # the `./` chars from the examples
+      - PATH=. arduino-lint ../docs/commands
+      - task: docs:format
+
+  docs:build:
+    desc: Build documentation website contents
+    cmds:
+      - task: docs:gen
+      - poetry install --no-root
+      - poetry run mkdocs build --strict
+
+  docs:publish:
+    desc: Use Mike to build and push versioned docs
+    cmds:
+      - task: docs:gen
+      - poetry run mike deploy --update-aliases --push --remote {{.DOCS_REMOTE}} {{.DOCS_VERSION}} {{.DOCS_ALIAS}}
+
+  docs:serve:
+    desc: Run documentation website locally
+    cmds:
+      - task: docs:build
+      - poetry run mkdocs serve
+
+  docs:check:
+    desc: Lint and check formatting of documentation files
+    cmds:
+      - task: docs:check-formatting
+      - task: markdown:lint
+      - task: markdown:fix
+      - task: markdown:check-links
+
+  docs:lint:
+    desc: Lint documentation files
+    cmds:
+      - task: docs:check-license
+
+  docs:check-license:
+    desc: Check if the license file is correctly formatted
+    cmds:
+      - |
+        EXPECTED_LICENSE_FILE="\"LICENSE.txt\""
+        EXPECTED_LICENSE_TYPE="\"GPL-3.0\"" # https://spdx.org/licenses/
+
+        # See: https://github.com/licensee/licensee
+        LICENSEE_OUTPUT="$(licensee detect --json --confidence=100)"
+
+        DETECTED_LICENSE_FILE="$(echo "$LICENSEE_OUTPUT" | jq .matched_files[0].filename | tr --delete '\r')"
+        echo "Detected license file: $DETECTED_LICENSE_FILE"
+        if [ "$DETECTED_LICENSE_FILE" != "$EXPECTED_LICENSE_FILE" ]; then
+          echo "ERROR: detected license file doesn't match expected: $EXPECTED_LICENSE_FILE"
+          exit 1
+        fi
+
+        DETECTED_LICENSE_TYPE="$(echo "$LICENSEE_OUTPUT" | jq .matched_files[0].matched_license | tr --delete '\r')"
+        echo "Detected license type: $DETECTED_LICENSE_TYPE"
+        if [ "$DETECTED_LICENSE_TYPE" != "$EXPECTED_LICENSE_TYPE" ]; then
+          echo "ERROR: detected license type doesn't match expected $EXPECTED_LICENSE_TYPE"
+          exit 1
         fi
 
   docs:check-formatting:
