Alphabetize tasks
I originally set out to establish some logical order to the tasks, based partly on the Arduino CLI taskfile, as that
project was used as a model, then on some indecipherable criteria of my own devizing in cases where the model did not
provide guidance. In the end, it resulted in a jumble.

Alphabetical order is completely objective and it results in a fairly logical order in the end due to the the use of
prefixes on the task names according to their domain. The exception is that the convenience "umbrella" tasks have been
left at the top (in their own alphabetical order) so that they will have the maximum visibility as the most useful tasks.
Even that is not completely inconsistent, since these don't have a namespace prefix, and so might be imagined to have a
null global namespace prefix that would be sorted first.

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -35,6 +35,23 @@ tasks:
     deps:
       - task: go:build
 
+  check:
+    desc: Check for problems with the project
+    cmds:
+      - task: ci:validate
+      - task: general:check-formatting
+      - task: general:check-spelling
+      - task: go:test
+      - task: go:test-integration
+      - task: go:vet
+      - task: go:lint
+      - task: markdown:lint
+      - task: markdown:check-links
+      - task: python:lint
+      - task: shell:check
+      - task: shell:check-mode
+      - task: website:check
+
   fix:
     desc: Make automated corrections to the project's files
     deps:
@@ -47,11 +64,100 @@ tasks:
       - task: python:format
       - task: shell:format
 
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-workflows-task/Taskfile.yml
+  ci:validate:
+    desc: Validate GitHub Actions workflows against their JSON schema
+    vars:
+      # Source: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json
+      WORKFLOW_SCHEMA_URL: https://json.schemastore.org/github-workflow
+      WORKFLOW_SCHEMA_PATH:
+        sh: mktemp -t workflow-schema-XXXXXXXXXX.json
+      WORKFLOWS_DATA_PATH: "./.github/workflows/*.{yml,yaml}"
+    cmds:
+      - |
+        wget \
+          --quiet \
+          --output-document="{{.WORKFLOW_SCHEMA_PATH}}" \
+          {{.WORKFLOW_SCHEMA_URL}}
+      - |
+        npx \
+          --package=ajv-cli \
+          --package=ajv-formats \
+          ajv validate \
+            --all-errors \
+            --strict=false \
+            -c ajv-formats \
+            -s "{{.WORKFLOW_SCHEMA_PATH}}" \
+            -d "{{.WORKFLOWS_DATA_PATH}}"
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/deploy-cobra-mkdocs-versioned-poetry/Taskfile.yml
+  docs:generate:
+    desc: Create all generated documentation content
+    deps:
+      - task: go:cli-docs
+      # Make the formatting consistent with the non-generated Markdown
+      - task: general:format-prettier
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-general-formatting-task/Taskfile.yml
+  general:check-formatting:
+    desc: Check basic formatting style of all files
+    cmds:
+      - |
+        if ! which ec &>/dev/null; then
+          echo "ec not found or not in PATH. Please install: https://github.com/editorconfig-checker/editorconfig-checker#installation"
+          exit 1
+        fi
+      - ec
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/spell-check-task/Taskfile.yml
+  general:check-spelling:
+    desc: Check for commonly misspelled words
+    deps:
+      - task: poetry:install-deps
+    cmds:
+      - poetry run codespell
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/spell-check-task/Taskfile.yml
+  general:correct-spelling:
+    desc: Correct commonly misspelled words where possible
+    deps:
+      - task: poetry:install-deps
+    cmds:
+      - poetry run codespell --write-changes
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-prettier-formatting-task/Taskfile.yml
+  general:format-prettier:
+    desc: Format all supported files with Prettier
+    cmds:
+      - npx prettier --write .
+
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/go-task/Taskfile.yml
   go:build:
     desc: Build the Go code
     cmds:
       - go build -v {{.LDFLAGS}}
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/deploy-cobra-mkdocs-versioned-poetry/Taskfile.yml
+  go:cli-docs:
+    desc: Generate command line interface reference documentation
+    dir: ./docsgen
+    cmds:
+      # Command examples use os.Args[0] so the docs generation binary must have the same filename as the project
+      - go build -o {{.PROJECT_NAME}}{{exeExt}}
+      # The binary is invoked like this instead of `./{{.PROJECT_NAME}}` to remove the `./` chars from the examples
+      - PATH=. {{.PROJECT_NAME}} ../docs/commands
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
+  go:fix:
+    desc: Modernize usages of outdated APIs
+    cmds:
+      - go fix {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
+  go:format:
+    desc: Format Go code
+    cmds:
+      - go fmt {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}
 
   go:generate:
     desc: Generate Go code
@@ -62,6 +168,20 @@ tasks:
       - go install golang.org/x/tools/cmd/stringer@v0.0.0-20201211192254-72fbef54948b
       - go generate ./...
       - task: go:format
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
+  go:lint:
+    desc: Lint Go code
+    cmds:
+      - |
+        if ! which golint &>/dev/null; then
+          echo "golint not installed or not in PATH. Please install: https://github.com/golang/lint#installation"
+          exit 1
+        fi
+      - |
+        golint \
+          {{default "-min_confidence 0.8 -set_exit_status" .GO_LINT_FLAGS}} \
+          {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}
 
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/test-go-task/Taskfile.yml
   go:test:
@@ -85,66 +205,11 @@ tasks:
     cmds:
       - poetry run pytest tests
 
-  check:
-    desc: Check for problems with the project
-    cmds:
-      - task: ci:validate
-      - task: general:check-formatting
-      - task: general:check-spelling
-      - task: go:test
-      - task: go:test-integration
-      - task: go:vet
-      - task: go:lint
-      - task: markdown:lint
-      - task: markdown:check-links
-      - task: python:lint
-      - task: shell:check
-      - task: shell:check-mode
-      - task: website:check
-
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
   go:vet:
     desc: Check for errors in Go code
     cmds:
       - go vet {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
-  go:fix:
-    desc: Modernize usages of outdated APIs
-    cmds:
-      - go fix {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
-  go:lint:
-    desc: Lint Go code
-    cmds:
-      - |
-        if ! which golint &>/dev/null; then
-          echo "golint not installed or not in PATH. Please install: https://github.com/golang/lint#installation"
-          exit 1
-        fi
-      - |
-        golint \
-          {{default "-min_confidence 0.8 -set_exit_status" .GO_LINT_FLAGS}} \
-          {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-task/Taskfile.yml
-  go:format:
-    desc: Format Go code
-    cmds:
-      - go fmt {{default .DEFAULT_GO_PACKAGES .GO_PACKAGES}}
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
-  markdown:lint:
-    desc: Check for problems in Markdown files
-    cmds:
-      - npx markdownlint-cli "**/*.md"
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
-  markdown:fix:
-    desc: Automatically correct linting violations in Markdown files where possible
-    cmds:
-      - npx markdownlint-cli --fix "**/*.md"
 
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
   markdown:check-links:
@@ -189,6 +254,18 @@ tasks:
           '
         fi
 
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
+  markdown:fix:
+    desc: Automatically correct linting violations in Markdown files where possible
+    cmds:
+      - npx markdownlint-cli --fix "**/*.md"
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
+  markdown:lint:
+    desc: Check for problems in Markdown files
+    cmds:
+      - npx markdownlint-cli "**/*.md"
+
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/poetry-task/Taskfile.yml
   poetry:install-deps:
     desc: Install dependencies managed by Poetry
@@ -202,14 +279,6 @@ tasks:
       - poetry update
 
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-python-task/Taskfile.yml
-  python:lint:
-    desc: Lint Python code
-    deps:
-      - task: poetry:install-deps
-    cmds:
-      - poetry run flake8 --show-source
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-python-task/Taskfile.yml
   python:format:
     desc: Format Python files
     deps:
@@ -217,41 +286,13 @@ tasks:
     cmds:
       - poetry run black .
 
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/deploy-cobra-mkdocs-versioned-poetry/Taskfile.yml
-  docs:generate:
-    desc: Create all generated documentation content
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-python-task/Taskfile.yml
+  python:lint:
+    desc: Lint Python code
     deps:
-      - task: go:cli-docs
-      # Make the formatting consistent with the non-generated Markdown
-      - task: general:format-prettier
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/deploy-cobra-mkdocs-versioned-poetry/Taskfile.yml
-  go:cli-docs:
-    desc: Generate command line interface reference documentation
-    dir: ./docsgen
-    cmds:
-      # Command examples use os.Args[0] so the docs generation binary must have the same filename as the project
-      - go build -o {{.PROJECT_NAME}}{{exeExt}}
-      # The binary is invoked like this instead of `./{{.PROJECT_NAME}}` to remove the `./` chars from the examples
-      - PATH=. {{.PROJECT_NAME}} ../docs/commands
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-mkdocs-task/Taskfile.yml
-  website:check:
-    desc: Check whether the MkDocs-based website will build
-    deps:
-      - task: docs:generate
       - task: poetry:install-deps
     cmds:
-      - poetry run mkdocs build --strict
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-mkdocs-task/Taskfile.yml
-  website:serve:
-    desc: Run website locally
-    deps:
-      - task: docs:generate
-      - task: poetry:install-deps
-    cmds:
-      - poetry run mkdocs serve
+      - poetry run flake8 --show-source
 
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-shell-task/Taskfile.yml
   shell:check:
@@ -282,17 +323,6 @@ tasks:
           )
 
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-shell-task/Taskfile.yml
-  shell:format:
-    desc: Format shell script files
-    cmds:
-      - |
-        if ! which shfmt &>/dev/null; then
-          echo "shfmt not installed or not in PATH. Please install: https://github.com/mvdan/sh#shfmt"
-          exit 1
-        fi
-      - shfmt -w .
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-shell-task/Taskfile.yml
   shell:check-mode:
     desc: Check for non-executable shell scripts
     cmds:
@@ -321,61 +351,31 @@ tasks:
         )"
         exit $EXIT_STATUS
 
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-workflows-task/Taskfile.yml
-  ci:validate:
-    desc: Validate GitHub Actions workflows against their JSON schema
-    vars:
-      # Source: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json
-      WORKFLOW_SCHEMA_URL: https://json.schemastore.org/github-workflow
-      WORKFLOW_SCHEMA_PATH:
-        sh: mktemp -t workflow-schema-XXXXXXXXXX.json
-      WORKFLOWS_DATA_PATH: "./.github/workflows/*.{yml,yaml}"
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-shell-task/Taskfile.yml
+  shell:format:
+    desc: Format shell script files
     cmds:
       - |
-        wget \
-          --quiet \
-          --output-document="{{.WORKFLOW_SCHEMA_PATH}}" \
-          {{.WORKFLOW_SCHEMA_URL}}
-      - |
-        npx \
-          --package=ajv-cli \
-          --package=ajv-formats \
-          ajv validate \
-            --all-errors \
-            --strict=false \
-            -c ajv-formats \
-            -s "{{.WORKFLOW_SCHEMA_PATH}}" \
-            -d "{{.WORKFLOWS_DATA_PATH}}"
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-general-formatting-task/Taskfile.yml
-  general:check-formatting:
-    desc: Check basic formatting style of all files
-    cmds:
-      - |
-        if ! which ec &>/dev/null; then
-          echo "ec not found or not in PATH. Please install: https://github.com/editorconfig-checker/editorconfig-checker#installation"
+        if ! which shfmt &>/dev/null; then
+          echo "shfmt not installed or not in PATH. Please install: https://github.com/mvdan/sh#shfmt"
           exit 1
         fi
-      - ec
+      - shfmt -w .
 
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-prettier-formatting-task/Taskfile.yml
-  general:format-prettier:
-    desc: Format all supported files with Prettier
-    cmds:
-      - npx prettier --write .
-
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/spell-check-task/Taskfile.yml
-  general:check-spelling:
-    desc: Check for commonly misspelled words
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-mkdocs-task/Taskfile.yml
+  website:check:
+    desc: Check whether the MkDocs-based website will build
     deps:
+      - task: docs:generate
       - task: poetry:install-deps
     cmds:
-      - poetry run codespell
+      - poetry run mkdocs build --strict
 
-  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/spell-check-task/Taskfile.yml
-  general:correct-spelling:
-    desc: Correct commonly misspelled words where possible
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-mkdocs-task/Taskfile.yml
+  website:serve:
+    desc: Run website locally
     deps:
+      - task: docs:generate
       - task: poetry:install-deps
     cmds:
-      - poetry run codespell --write-changes
+      - poetry run mkdocs serve
