Don't use Task for license check
Task provides a convenient way to run common development processes locally with a single command. But I don't think the
need to check the license file is common, nor something anyone would bother running. Instead, it's something that can be
added to the repository and forgotten until the day comes that someone mucks around with the license file. That person
likely would not have been aware of the existence of the task.

diff --git a/.github/workflows/check-license.yml b/.github/workflows/check-license.yml
--- a/.github/workflows/check-license.yml
+++ b/.github/workflows/check-license.yml
@@ -1,10 +1,14 @@
 name: Check License
 
+env:
+  EXPECTED_LICENSE_FILENAME: LICENSE.txt
+  # SPDX identifier: https://spdx.org/licenses/
+  EXPECTED_LICENSE_TYPE: GPL-3.0
+
 on:
   push:
     paths:
       - ".github/workflows/check-license.ya?ml"
-      - "Taskfile.yml"
       # Recognized license files. See: https://github.com/licensee/licensee/blob/master/docs/what-we-look-at.md#detecting-the-license-file
       - "COPYING*"
       - "LICENCE*"
@@ -12,7 +16,6 @@ on:
   pull_request:
     paths:
       - ".github/workflows/check-license.ya?ml"
-      - "Taskfile.yml"
       - "COPYING*"
       - "LICENCE*"
       - "LICENSE*"
@@ -25,12 +28,6 @@ jobs:
       - name: Checkout local repository
         uses: actions/checkout@v2
 
-      - name: Install Taskfile
-        uses: arduino/setup-task@v1
-        with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-          version: 3.x
-
       - uses: ruby/setup-ruby@v1
         with:
           ruby-version: ruby # Install latest version
@@ -40,4 +37,20 @@ jobs:
 
       # See: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository
       - name: Check license file
-        run: task --silent docs:check-license
+        run: |
+          # See: https://github.com/licensee/licensee
+          LICENSEE_OUTPUT="$(licensee detect --json --confidence=100)"
+
+          DETECTED_LICENSE_FILE="$(echo "$LICENSEE_OUTPUT" | jq .matched_files[0].filename | tr --delete '\r')"
+          echo "Detected license file: $DETECTED_LICENSE_FILE"
+          if [ "$DETECTED_LICENSE_FILE" != "\"${EXPECTED_LICENSE_FILENAME}\"" ]; then
+            echo "ERROR: detected license file doesn't match expected: $EXPECTED_LICENSE_FILENAME"
+            exit 1
+          fi
+
+          DETECTED_LICENSE_TYPE="$(echo "$LICENSEE_OUTPUT" | jq .matched_files[0].matched_license | tr --delete '\r')"
+          echo "Detected license type: $DETECTED_LICENSE_TYPE"
+          if [ "$DETECTED_LICENSE_TYPE" != "\"${EXPECTED_LICENSE_TYPE}\"" ]; then
+            echo "ERROR: detected license type doesn't match expected $EXPECTED_LICENSE_TYPE"
+            exit 1
+          fi
